apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{.Values.name}}
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description:  {{.Values.name}} project

  sourceNamespaces:
  - {{.Values.name}}
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: {{.Values.name}}
    server: https://kubernetes.default.svc

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy

  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet
  - group: ''
    kind: Service
  - group: ''
    kind: Secret
  - group: ''
    kind: ConfigMap
  - group: 'rbac.authorization.k8s.io'
    kind: Role
  - group: 'rbac.authorization.k8s.io'
    kind: RoleBinding
  - group: ''
    kind: ServiceAccount
  - group: 'autoscaling'
    kind: HorizontalPodAutoscaler
  - group: 'policy'
    kind: PodDisruptionBudget
  - group: 'batch'
    kind: Job
  - group: 'networking.istio.io'
    kind: Gateway
  - group: 'cert-manager.io'
    kind: Issuer
  - group: 'networking.k8s.io'
    kind: Ingress
  - group: 'monitoring.coreos.com'
    kind: '*'
  - group: ''
    kind: PersistentVolumeClaim
  - group: 'networking.istio.io'
    kind: VirtualService

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

  roles:
  # A role which provides read-only access to all applications in the project
  - name: admin
    description: admin privileges to {{.Values.name}}
    policies:
    - p, proj:{{.Values.name}}:admin, applications, *, {{.Values.name}}/*, allow
    - p, proj:{{.Values.name}}:admin, repositories, *, {{.Values.name}}/*, allow
    - p, proj:{{.Values.name}}:admin, clusters, get, *, allow
    - p, proj:{{.Values.name}}:admin, logs, get, {{.Values.name}}/*, allow
    groups:
    - {{.Values.name}}
